# Generated by Django 5.2.9 on 2025-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la tarea')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('horas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Invertidas')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('completada', models.BooleanField(default=False, verbose_name='¿Completada?')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-fecha'],
            },
        ),
    ]
