# Generated by Django 5.2.9 on 2025-12-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_departamento_empleado_periodo_registrohora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Secretaría'),
        ),
    ]
