# Generated by Django 5.2.9 on 2025-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_secretaria_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretaria',
            options={'ordering': ['imputacion'], 'verbose_name': 'Secretaría', 'verbose_name_plural': 'Secretarías'},
        ),
        migrations.AddField(
            model_name='secretaria',
            name='imputacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Imputación'),
        ),
    ]
