# Generated by Django 5.2.9 on 2025-12-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_secretaria_options_secretaria_imputacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='imputacion',
            field=models.CharField(default='00.00', max_length=10, verbose_name='Imputación'),
        ),
    ]
