# Generated by Django 5.2.9 on 2025-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_secretaria_imputacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['secretaria', 'imputacion'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='imputacion',
            field=models.CharField(default='00', max_length=10, verbose_name='Imputación'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento'),
        ),
    ]
