# Generated by Django 5.2.9 on 2025-12-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_departamento_options_departamento_imputacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='¿Cerrado Totalmente?'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Visible?'),
        ),
    ]
