# Generated by Django 5.2.9 on 2025-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_periodo_cerrado_alter_periodo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='activo',
        ),
        migrations.AddField(
            model_name='periodo',
            name='vigente',
            field=models.BooleanField(default=False, verbose_name='¿Es el Período Vigente?'),
        ),
    ]
