# Generated by Django 5.2.9 on 2025-12-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_remove_periodo_activo_periodo_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohora',
            name='autorizado_exceso',
            field=models.BooleanField(default=False, help_text='Marcar para permitir cargar más de 180 horas.', verbose_name='¿Autorizar Exceso (+180hs)?'),
        ),
        migrations.AddField(
            model_name='registrohora',
            name='otro_departamento',
            field=models.ForeignKey(blank=True, help_text='Seleccionar SOLO si las horas se cobran a un área distinta a la del empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.departamento', verbose_name='¿Imputar a otra Área?'),
        ),
    ]
