# Generated by Django 5.2.9 on 2025-12-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_registrohora_autorizado_exceso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohora',
            name='descripcion',
        ),
    ]
