"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d3hdt62m$@1uv00=s^0g42#j#qs!bq%5ez$9%*rquas8hwmv^)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'admin_reorder',      # Para ordenar el panel principal
    'jazzmin',            # El tema visual
    'import_export',      # Para importar Excel
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tareas',             # Tu aplicación principal
    'simple_history',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',  # Middleware de ordenamiento
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ESTA ES LA LÍNEA CLAVE QUE DEBES CORREGIR:
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "core/static"),
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# CONFIGURACIÓN DE JAZZMIN (CORREGIDA)
# ==========================================

JAZZMIN_SETTINGS = {
    # Títulos y Logo
    "site_title": "Muni Chajarí",
    "site_header": "Gestión Municipal",
    "site_brand": "Muni Chajarí",
    "site_logo": "img/logo_chico.png",
    "site_logo_classes": "img-circle",

    # Textos
    "welcome_sign": "Bienvenido al Sistema de Gestión de Horas Adicionales",
    "copyright": "by Chapit'as",

    # Menú lateral
    "show_sidebar": True,
    "navigation_expanded": True,

    # ÍCONOS
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        
        # TUS MÓDULOS
        "tareas.Secretaria": "fas fa-building",
        "tareas.Departamento": "fas fa-network-wired",
        "tareas.Empleado": "fas fa-id-card",
        "tareas.Periodo": "fas fa-calendar-alt",
        "tareas.RegistroHora": "fas fa-clock",
    },

    # ORDEN DEL MENÚ LATERAL (Barra izquierda)
    "order_with_respect_to": [
        "auth",
        "tareas",
        "tareas.Secretaria",
        "tareas.Departamento",
        "tareas.Empleado",
        "tareas.Periodo",
        "tareas.RegistroHora",
    ],

    # ARCHIVOS PERSONALIZADOS (JS y CSS)
    "custom_js": "js/login.js",
    "custom_css": "css/custom_admin.css",
}

# Ajustes visuales extra (UI Tweaks)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "theme": "theme",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# ==========================================
# ORDEN DEL MENÚ PRINCIPAL (BOTONES CENTRALES)
# ==========================================

ADMIN_REORDER = (
    {'app': 'auth', 'label': 'Usuarios y Seguridad', 'models': ('auth.User', 'auth.Group')},
    {'app': 'tareas', 'label': 'Módulos', 'models': (
        'tareas.Secretaria',
        'tareas.Departamento',
        'tareas.Empleado',
        'tareas.Periodo',
        'tareas.RegistroHora',
    )},
)